#! ruby
require 'test/unit'
require 'entropia'

class TestEntropia < Test::Unit::TestCase
  include ENTROPIA

  def test_000_digests
    string = '123abc'
    n = Entropia.new string, base:16, digits: '0123456789abcdef'
    data = n.data
    assert_equal Digest::SHA2.new(256).hexdigest(data), n.sha2.to_s
    assert_equal Digest::SHA2.new(512).hexdigest(data), n.sha2(512).to_s
    assert_equal Digest::SHA1.hexdigest(data),          n.sha1.to_s
    assert_equal Digest::MD5.hexdigest(data),           n.md5.to_s
    assert_equal Digest::RMD160.hexdigest(data),        n.rmd160.to_s
  end
end
